name: atamnirbharapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eva_icons_flutter: ^2.0.1
  fab_circular_menu: ^1.0.0
  flutter_launcher_icons: ^0.8.0
  font_awesome_flutter: ^8.8.1
  flutter_signin_button: ^0.2.8
  carousel_slider: ^2.3.1
  flutter_auth_buttons: ^0.10.0
  flutter_otp: ^0.3.2
  http: ^0.12.2
  shared_preferences: ^0.5.2
  firebase_auth: ^0.18.1+2
  flutter_html_view: ^0.5.12
  firebase_messaging: ^7.0.3
  firebase_core : ^0.5.0
  pin_code_fields: ^6.0.0
  country_code_picker: ^1.6.0
  country_pickers: ^1.3.0
  flutter_country_picker: ^0.1.6
  cloud_firestore: ^0.14.1+3
  json_serializable: ^3.5.0
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  path: ^1.7.0
  webview_flutter: ^1.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  image_path: "assets/images/Final_AatmNirbhar_logo.png"
  android: true
  ios: true
  
flutter:
  assets:
    - assets/images/BG_Color.jpeg
    - assets/images/sidebar_dash_icon.png
    - assets/images/Final_AatmNirbhar_logo.png
    - assets/images/MakeInIndiaLogo.png
    - assets/images/Hersheys_Company_Logo.png
    - assets/images/PreferThis.png
    - assets/images/MakesInIndia_Logo.png
    - assets/images/USA_flag.png
    - assets/images/backimage.jpg
    - assets/images/britannia.png
    - assets/images/Cars.png
    - assets/images/Jewellery.png
    - assets/images/Medicines.png
    - assets/images/Smart Phones.png
    - assets/images/Toys.png
    - assets/images/Televisions.png
    - assets/images/Bajaj_Company_logo.png
    - assets/images/Indian_Flag.png
    - assets/images/Fact_Icon.png
    - assets/images/Wikipedia_Icon.png
    - assets/images/Website_Icon.png
    - assets/images/Dani.jpeg
    - assets/images/Prathm.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
