name: atamnirbharapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.3.1
  http: ^0.12.2
  firebase_auth: ^0.18.1+2
  flutter_html_view: ^0.5.12
  firebase_messaging: ^7.0.3
  firebase_core : ^0.5.0
  flutter_country_picker: ^0.1.6
  cloud_firestore: ^0.14.1+3
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  webview_flutter: ^1.0.5
  google_sign_in: ^4.5.3
  intl: ^0.16.1
  youtube_player_flutter: ^7.0.0+7
  url_launcher: ^5.7.10
  connectivity: ^0.4.5+3
  flutter_offline: ^0.3.0
  video_player: 0.10.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

  
flutter:
  assets:
    - assets/images/BG_Color.jpeg
    - assets/images/sidebar_dash_icon.png
    - assets/images/Final_AatmNirbhar_logo.png
    - assets/images/MakeInIndiaLogo.png
    - assets/images/PreferThis.png
    - assets/images/MakesInIndia_Logo.png
    - assets/images/Indian_Flag.png
    - assets/images/Fact_Icon.png
    - assets/images/Website_Icon.png
    - assets/images/glogo.png
    - assets/images/indian_flag_icon.png
    - assets/images/Products_Icon.png
    - assets/images/Imported_Icon.png
    - assets/images/alternatives_icon.png
    - assets/images/Wikipedia_Icon.png
    - assets/video/Opening_Animation_The_Aatmanirbhar_App.mp4
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
       - asset: assets/fonts/roboto/Roboto-Black.ttf
       - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
       - asset: assets/fonts/roboto/Roboto-Bold.ttf
       - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
       - asset: assets/fonts/roboto/Roboto-Italic.ttf
       - asset: assets/fonts/roboto/Roboto-Light.ttf
       - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
       - asset: assets/fonts/roboto/Roboto-Medium.ttf
       - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
       - asset: assets/fonts/roboto/Roboto-Regular.ttf
       - asset: assets/fonts/roboto/Roboto-Thin.ttf
       - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
    - family: OpenSans
      fonts:
       - asset: assets/fonts/opensans/OpenSans-Bold.ttf
       - asset: assets/fonts/opensans/OpenSans-BoldItalic.ttf
       - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
       - asset: assets/fonts/opensans/OpenSans-ExtraBoldItalic.ttf
       - asset: assets/fonts/opensans/OpenSans-Italic.ttf
       - asset: assets/fonts/opensans/OpenSans-Light.ttf
       - asset: assets/fonts/opensans/OpenSans-LightItalic.ttf
       - asset: assets/fonts/opensans/OpenSans-Regular.ttf
       - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
       - asset: assets/fonts/opensans/OpenSans-SemiBoldItalic.ttf
    - family: Ambit
      fonts:
       - asset: assets/fonts/Ambit/Ambit-Black.ttf
       - asset: assets/fonts/Ambit/Ambit-BlackItalic.ttf
       - asset: assets/fonts/Ambit/Ambit-Bold.ttf
       - asset: assets/fonts/Ambit/Ambit-BoldItalic.ttf
       - asset: assets/fonts/Ambit/Ambit-ExtraLight.ttf
       - asset: assets/fonts/Ambit/Ambit-ExtraLightItalic.ttf
       - asset: assets/fonts/Ambit/Ambit-Italic.ttf
       - asset: assets/fonts/Ambit/Ambit-Light.ttf
       - asset: assets/fonts/Ambit/Ambit-LightItalic.ttf
       - asset: assets/fonts/Ambit/Ambit-Regular.ttf
       - asset: assets/fonts/Ambit/Ambit-SemiBold.ttf
       - asset: assets/fonts/Ambit/Ambit-SemiBoldItalic.ttf
       - asset: assets/fonts/Ambit/Ambit-Thin.ttf
       - asset: assets/fonts/Ambit/Ambit-ThinItalic.ttf